name: bloc_news
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  get_it: ^7.6.4
  intl: ^0.18.1
  ionicons: ^0.2.2
  retrofit: ^4.0.3

dev_dependencies:
  build_runner: ^2.4.7
  floor_generator: ^1.4.2
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.0.5
flutter:
  uses-material-design: true
